name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
runs:
  using: composite
  steps:
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-bazel
    - name: Build Swift extractor
      shell: bash
      run: |
        bazel run //swift:create-extractor-pack
