name: "Swift: Run QL Tests"

on:
  pull_request:
    paths:
      - "swift/**"
      - .github/workflows/swift-qltest.yml
      - codeql-workspace.yml
    branches:
      - main
defaults:
  run:
    working-directory: swift

jobs:
  qlformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fetch-codeql
      - name: Check QL formatting
        run: find ql "(" -name "*.ql" -or -name "*.qll" ")" -print0 | xargs -0 codeql query format --check-only
  qltest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-20.04, macos-latest]
        slice: [ "1/3", "2/3", "3/3" ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fetch-codeql
      - name: Create extractor pack
        uses: ./swift/actions/create-extractor-pack
      - name: Mount CodeQL test cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/swift/ql/test/.cache
          key: ${{ runner.os }}-swift-ql-test
      - name: Run QL tests
        run: |
          codeql test run --threads=0 --ram 5000 --slice ${{ matrix.slice }} --search-path "${{ github.workspace }}/swift/extractor-pack" --check-databases --check-unused-labels --check-repeated-labels --check-redefined-labels --check-use-before-definition ql/test
        env:
          GITHUB_TOKEN: ${{ github.token }}
